### PR TITLE
Update dependants upon PR merged or issue closed webhook events

### LINKED ISSUE #29: Add the ability to observe the the dependencies and update the dependent PR
# Summary
Pierre should be able to check the dependencies for any given PR without the need of an event.

Once that dependency is added to a PR, Pierre should keep track of both for status changes.

# To Keep In Mind
Even thought this feels like a standard behavior, tools like [Jenkins](https://jenkins.io) still rely on events from the PR (`Jenkins please` in order to re-run the tests).

Also, **this is important**, Pierre should remain as small-projects-friendly as possible. Meaning that if this feature should be implemented, it should be behind of a **feature flag** (in the form of a `environment variable`), so that if it requires more resources (database, task queue, automated jobs, etc) people that cannot afford them  will still able to use Pierre.

# Thanks
To @supernova32 for suggesting this feature 😃

### PR DESCRIPTION
**Pull request by pomu0325**
# What we're fixing

Fixes #29

## Limitations
In order to update check status upon issue closed, `Issues` event must be added to webhook configuration (added to README).

This flow should also work with external repository, but only when both repositories for dependant PR and dependency PR/issue are configured to send webhook toward same pierre-decheck server.

# What we've done here

Let's say that `#1` depends on `#2` ,

1. Receive webhook upon pull_request (`#2`) merged, or issue closed 
2. Retrieve cross referenced PR (`#1`) from timeline of `#2` using [Timeline github api](https://developer.github.com/v3/issues/timeline/)
3. Re-run check for `#1`, dependency status should be updated to resolved

pierre-decheck 1
 

# How to verify these changes

1. Create a PR (e.g. `#1`)
2. Create another PR or an issue (e.g. `#2`)
3. Update `#1` comment to mark dependency to `#2`, now `#1`'s dependency status is updated to `not met`
4. Close `#2`, ✅ now `#1`'s dependency status is updated to `met`

### CODE REVIEW

**Review by alvarocavalcanti — APPROVED** [review]
LGTM

Awesome

**Comment by alvarocavalcanti** [comment]
@pomu0325 I've merged the first PR and now you need to fix a couple conflicts in this one

**Comment by pomu0325** [comment]
@alvarocavalcanti Thanks for the review :)
I've just rebased to current master and resolved conflicts 👍

**Comment by alvarocavalcanti** [comment]
pierre check

**Pull request merged**
