### PR TITLE
Fix circleci workflow

### PR DESCRIPTION
**Pull request by pomu0325**
# What we're fixing
Builds in Circle CI are failing.

# What we've done here
Fix Circle CI config.

# How to verify these changes
https://app.circleci.com/pipelines/github/pomu0325/pierre-decheck/7/workflows/168b8bcc-872f-4d92-83b3-04f70b32705a

### CODE REVIEW

**Comment by pomu0325** [comment]
@alvarocavalcanti Please look into repository settings and follow the steps described in https://circleci.com/docs/2.0/workflows-waiting-status/

**Review by alvarocavalcanti — APPROVED** [review]
LGTM

**Comment by alvarocavalcanti** [comment]
Thanks for this @pomu0325 I tried looking for this information last night but could not find it. :)

**Comment by pomu0325** [comment]
I think something is wrong on the settings at circleci side :(
https://app.circleci.com/pipelines/github/alvarocavalcanti/pierre-decheck/

**Comment by alvarocavalcanti** [comment]
Yeah, that's what it seemed to me as well. That's what I was trying to fix. Let's see if your changes addressed that. Although I've installed the `circleci` cli tool and it said that the YAML file was valid.

**Comment by alvarocavalcanti** [comment]
I'm gonna give it another go this evening

**Pull request merged**
