### PR TITLE
Docker environment

### LINKED ISSUE #61: Create a docker environment
We should have a `docker-composer.yml` that creates not only a container for the web app, but that also creates a sidecar container to be used as a remote interpreter by the IDE.

### LINKED ISSUE #65: Silence logger messages during test execution
When we execute the tests we get a lot of noise from `logger.info`. We should silence those.

### PR DESCRIPTION
**Pull request by alvarocavalcanti**
# What we're fixing

Fixes #61 
Fixes #65 

# What we've done here

- Added Docker and docker-composer support
- Standardized all the tests, making sure all test methods get executed
- Silenced logging messages when executing tests

# How to verify these changes

1. Checkout the branch
1. Type `make help` in the console and verify that all the targets are listed
1. Verify that the commands below work:
    1. `make build`
    1. `make clean`
    1. `make run`
    1. `make up`
    1. `make shell-app`
    1. `make shell-dev`
    1. `make flake8`
    1. `make unittest`
    1. `make test`
1. (If PyCharm Pro is available) Ensure that the docker **sidecar** is executed and then follow the instruction to configure PyCharm to use the remote interpreter. Once it's configured:
    1. Open any Python file, delete an import line, find the warning for missing import, navigate the cursor to it and then hit `Option + Enter`. PyCharm should either offer options to import or add the import right away (if unambiguous)
    1. Navigate the keyboard cursor to a member and then hit `Cmd + B`. You should either be taken to its definition or (if you are already at its definition) a list of its usage will be displayed
    1. Open a test file, navigate the keyboard cursor into a test method and hit `Ctrl + Shift + R`, the selected test should be executed and the results displayed

### CODE REVIEW

**Comment by alvarocavalcanti** [comment]
check

**Comment by alvarocavalcanti** [comment]
check

**Comment by alvarocavalcanti** [comment]
check

**Comment by alvarocavalcanti** [comment]
check

**Review by mosheeshel — APPROVED** [review]
Looks good, I run all the new commands, connected to the remote docker and executed tests and others.
Pretty cool!
image

**Comment by mosheeshel** [comment]
Also thanks for inviting me as a collaborator, will try to be a good one!

**Comment by alvarocavalcanti** [comment]
I have been wanting to add this for a while, since it reflects what my current development environment is!

And it's my pleasure to have you as a collaborator, but don't sweat it, no pressure **at all**.

I just got to work on Pierre because it's been hackathon since Monday here at WP Engine! Unfortunately I was not able to get any volunteer but was able to do some discovery into #62 and fix some other stuff.

And I asked for your input on this PR because it's kinda big and you a very familiarized with the code. Thanks!

**Comment by alvarocavalcanti** [comment]
check

**Comment by mosheeshel** [comment]
> I have been wanting to add this for a while, since it reflects what my current development environment is!
> 
> And it's my pleasure to have you as a collaborator, but don't sweat it, no pressure **at all**.
> 
> I just got to work on Pierre because it's been hackathon since Monday here at WP Engine! Unfortunately I was not able to get any volunteer but was able to do some discovery into #62 and fix some other stuff.
> 
> And I asked for your input on this PR because it's kinda big and you a very familiarized with the code. Thanks!

This change looks great, because it can also help with testing the Lambda version of the code - I'll see if I can find some time to add another docker, one that allows defining AWS lambda backend. And allow creation of an integration test around that.

**Pull request merged**
