### PR TITLE
Prevents cyclic dependency in a PR

### PR DESCRIPTION
**Pull request by rajalakshmi-v15**

### CODE REVIEW

**Comment by rajalakshmi-v15** [comment]
Hi, @mosheeshel . I deleted the old branch and added the same changes to the new one. Refers to #43  and #51

**Review by mosheeshel — APPROVED** [review]
LGTM, @alvarocavalcanti I think you can merge

**Comment by rajalakshmi-v15** [comment]
@mosheeshel & @alvarocavalcanti, thank you for helping me make my first ever contribution  (hopefully) :smile:

**Comment by mosheeshel** [comment]
@rajalakshmi-v15 my pleasure, hope you had a good time and stick around for some more! are you using the project? can you tell us a bit about it? how did you get involved?

**Comment by rajalakshmi-v15** [comment]
Sure, @mosheeshel. I saw found this project in https://up-for-grabs.net/. I am not using it at present but would love to :smile: As a beginner, I found the code simple to understand and immediately start working on (though adding more comments to the code would definitely help). Working on the issue also helped me understand git more. Thanks for being so patient with me.

**Review by alvarocavalcanti — APPROVED** [review]
LGTM

**Comment by alvarocavalcanti** [comment]
@rajalakshmi-v15 Great to know that you found it there! And it's also a great feedback on the codebase as a whole, for you to be an inexperienced contributor but was able to find your way into the code.

On the documentation matter, I believe there's room for improvement, but my take on this isn't the usual one. I plan on enriching the README.md with a `Contributing` section in which I can write about the general architecture of the project, but I do not plan on adding code comments.

People with whom I've worked with sometimes joke about this, but I have a strong conviction that writing code comments is a bad habit. I strive to have a readable code base and a descriptive test suite, only aided by a general architecture document. As food for thought on the matter I would like to point you to [FunctionLength](https://martinfowler.com/bliki/FunctionLength.html) by Martin Fowler, and [DAMP vs DRY](https://stackoverflow.com/questions/6453235/what-does-damp-not-dry-mean-when-talking-about-unit-tests).

Then again, thanks for your contribution. 😁

**Comment by alvarocavalcanti** [comment]
Closes #43

**Pull request merged**
