### PR TITLE
Added support for dependency keywords with full issue/PR url

### PR DESCRIPTION
**Pull request by pomu0325**
# What we're fixing
Github supports linking with issue/PR url, so I wanted to write dependency like `Depends on https://github.com/alvarocavalcanti/pierre-decheck/pull/72`.
I usually use this style for linking to issues in external repo, because it's easier to copy and paste :)

see: https://help.github.com/en/github/writing-on-github/autolinked-references-and-urls#issues-and-pull-requests

# What we've done here
- support dependency keywords with full issue/PR url
- some improvements to regex pattern

# How to verify these changes
Run tests.

### CODE REVIEW

**Review by mosheeshel — CHANGES_REQUESTED** [review]
This looks good, thanks for the detailed tests!
Please also add documentation and examples of usage to the main README file to show the various ways to add a dependency.

**Review by alvarocavalcanti — CHANGES_REQUESTED** [review]
I second @mosheeshel in that the changes look good but we need an updated documentation.

Thanks for the contribution!

**Comment by pomu0325** [comment]
@mosheeshel @alvarocavalcanti Thanks for the review 😃  I've just updated the README.

**Review by mosheeshel — APPROVED** [review]
LGTM, thank you for adding to the docs.

**Review by alvarocavalcanti — APPROVED** [review]

**Pull request merged**
